// Copyright 2022 Shem Sedrick (@ssedrick)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define BOOTMAGIC_ROW_RIGHT 6
#define BOOTMAGIC_COLUMN_RIGHT 4

#define WS2812_PIO_USE_PIO1

#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE

#define RGBLED_NUM 40
#define RGB_MATRIX_LED_COUNT RGBLED_NUM
#define RGB_DISABLE_WHEN_USB_SUSPENDED

#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 255
#define RGB_MATRIX_DEFAULT_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS
#define RGB_MATRIX_SPLIT {20, 20}
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR

// Power settings
#define USB_MAX_POWER_CONSUMPTION 500
/* Trackball */
// #define SPI_DRIVER SPID0
// #define SPI_SCK_PIN GP18
// #define SPI_MISO_PIN GP20
// #define SPI_MOSI_PIN GP19
// #define PMW33XX_CS_PIN GP29
// #define PMW33XX_CPI 1600
// #define PMW33XX_LIFTOFF_DISTANCE 0x02
// #define POINTING_DEVICE_INVERT_Y
// #define ROTATIONAL_TRANSFORM_ANGLE -30 // Optional: Rotates the trackball
// #define ROTATIONAL_TRANSFORM_ANGLE 90
// #define POINTING_DEVICE_TASK_THROTTLE_MS 50
// #define POINTING_DEVICE_INVERT_X // Optional: Inverts trackball X
// #define SPLIT_POINTING_ENABLE
// #define POINTING_DEVICE_RIGHT
// #define POINTING_DEVICE_TASK_THROTTLE_MS 1
// #define POINTING_DEVICE_DEBUG

/* Reset */
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17
